//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysLanguages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysLanguages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن الشركة.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأسست شركة الأنسب لتجارة قطع غيار السيارات فى عام 2018 بمنطقة الزرقاء
        ///&lt;br&gt;
        ///مؤسسة الأنسب للسيارات هي الرائدة عالميا في مجال تصدير أبرز العلامات التجارية للسيارات في الأردن
        ///&lt;br&gt;
        ///وتقدم المؤسسة لعملائها في السوق الأردني خدمات بيع المركبات المستعملة وقطع الغيار والإكسسوارات وذلك من خلال مقر الشركة بالمنطقة الحرة-الزرقاء - الأردن.
        ///&lt;br&gt;
        ///كما أننا نعمل باستمرار على تطوير وتقديم حلول توريد مخصصة ومتكاملة لضمان جودة الخدمة ورضا العملاء..
        /// </summary>
        public static string AboutDetails {
            get {
                return ResourceManager.GetString("AboutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركة الأنسب لتجارة قطع الغيار السيارات بالمنطقة الحرة، الأردن.
        /// </summary>
        public static string AboutH2 {
            get {
                return ResourceManager.GetString("AboutH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامج لإدارة المخازن لقطع غيار السيارات، وفواتير البيع ، وحسابات العملاء.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحسابات.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصنيف الحساب.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشط.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل شراء سيارة جديدة.
        /// </summary>
        public static string AddANewCar {
            get {
                return ResourceManager.GetString("AddANewCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة فاتورة قطع غيار جديدة.
        /// </summary>
        public static string AddANewPartsInvoice {
            get {
                return ResourceManager.GetString("AddANewPartsInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل عملية قبض أو صرف أو تحويل بنكى..
        /// </summary>
        public static string AddANewPayments {
            get {
                return ResourceManager.GetString("AddANewPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة سيارة.
        /// </summary>
        public static string AddCar {
            get {
                return ResourceManager.GetString("AddCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة جديدة.
        /// </summary>
        public static string AddInvoice {
            get {
                return ResourceManager.GetString("AddInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دفع.
        /// </summary>
        public static string AddPayment {
            get {
                return ResourceManager.GetString("AddPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبض/صرف جديد.
        /// </summary>
        public static string AddPayments {
            get {
                return ResourceManager.GetString("AddPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنطقة الحرة - الزرقاء - الأردن.
        /// </summary>
        public static string AddressInJordan {
            get {
                return ResourceManager.GetString("AddressInJordan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأدمن.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض قائمة السيارات المسجلة بالنظام..
        /// </summary>
        public static string AllAvailableCarsList {
            get {
                return ResourceManager.GetString("AllAvailableCarsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجوع للقائمة.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجوع للقطع.
        /// </summary>
        public static string BackToPart {
            get {
                return ResourceManager.GetString("BackToPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخزينة/البنك.
        /// </summary>
        public static string BankCache {
            get {
                return ResourceManager.GetString("BankCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخزن/البنوك.
        /// </summary>
        public static string Banks {
            get {
                return ResourceManager.GetString("Banks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض قائمة الخزن والبنوك..
        /// </summary>
        public static string BanksAndCacheBoxes {
            get {
                return ResourceManager.GetString("BanksAndCacheBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركة الأنسب لتجارة قطع غيار السيارات.
        /// </summary>
        public static string Banner1P {
            get {
                return ResourceManager.GetString("Banner1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  الأنسب لتجارة قطع غيار السيارات هى شركة رائدة فى تجارة قطع غيار السيارات.
        /// </summary>
        public static string Banner2P {
            get {
                return ResourceManager.GetString("Banner2P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيارة.
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطع الغيار.
        /// </summary>
        public static string CarParts {
            get {
                return ResourceManager.GetString("CarParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيارات.
        /// </summary>
        public static string CarsList {
            get {
                return ResourceManager.GetString("CarsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر سيارة.
        /// </summary>
        public static string ChooseACar {
            get {
                return ResourceManager.GetString("ChooseACar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الحساب.
        /// </summary>
        public static string ChooseAccount {
            get {
                return ResourceManager.GetString("ChooseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الخزينة/البنك.
        /// </summary>
        public static string ChooseBank {
            get {
                return ResourceManager.GetString("ChooseBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر فاتورة.
        /// </summary>
        public static string ChooseInvoice {
            get {
                return ResourceManager.GetString("ChooseInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطابق القعطة مع السيارات.
        /// </summary>
        public static string Compatibilities {
            get {
                return ResourceManager.GetString("Compatibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطابق القعطة مع السيارة.
        /// </summary>
        public static string Compatibility {
            get {
                return ResourceManager.GetString("Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة قطعة جديدة.
        /// </summary>
        public static string CreateNewPart {
            get {
                return ResourceManager.GetString("CreateNewPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العميل.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إشعار حسابات بانتظار المراجعة.
        /// </summary>
        public static string CustomersAccountsToReview {
            get {
                return ResourceManager.GetString("CustomersAccountsToReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحسابات : عملاء، موردين ، ومندوبي المبيعات ..وو.
        /// </summary>
        public static string CustomersSupliersEtc {
            get {
                return ResourceManager.GetString("CustomersSupliersEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحركة اليومية.
        /// </summary>
        public static string DailyTransactionReport {
            get {
                return ResourceManager.GetString("DailyTransactionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع: قبض، صرف، تحويل بنكى ، أوراق مالية.
        /// </summary>
        public static string DebitCreditTransferType {
            get {
                return ResourceManager.GetString("DebitCreditTransferType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من حذف هذا البيان؟.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محذوفة.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصــم.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إشعار شيكات قيد التحصيل.
        /// </summary>
        public static string DueChecksCount {
            get {
                return ResourceManager.GetString("DueChecksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل بيانات السيارة.
        /// </summary>
        public static string EditCar {
            get {
                return ResourceManager.GetString("EditCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعة المحرك.
        /// </summary>
        public static string EngineName {
            get {
                return ResourceManager.GetString("EngineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعات المحرك.
        /// </summary>
        public static string Engines {
            get {
                return ResourceManager.GetString("Engines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من الخزينة/البنك.
        /// </summary>
        public static string FromBank {
            get {
                return ResourceManager.GetString("FromBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من/إلى الخزينة/البنك.
        /// </summary>
        public static string FromToBankCache {
            get {
                return ResourceManager.GetString("FromToBankCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من/إلى الشخص/الحساب.
        /// </summary>
        public static string FromToName {
            get {
                return ResourceManager.GetString("FromToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من سنة.
        /// </summary>
        public static string FromYear {
            get {
                return ResourceManager.GetString("FromYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموعة.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأقساط.
        /// </summary>
        public static string Installments {
            get {
                return ResourceManager.GetString("Installments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البضاعة.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة قطع غيار.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاتورة.
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فواتير قطع الغيار.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة فواتير قطع الغيار المسجلة..
        /// </summary>
        public static string InvoicesList {
            get {
                return ResourceManager.GetString("InvoicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رئيسي؟.
        /// </summary>
        public static string IsMain {
            get {
                return ResourceManager.GetString("IsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيارات.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنطقة.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المناطق.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع السيارة.
        /// </summary>
        public static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع السيارات.
        /// </summary>
        public static string Makes {
            get {
                return ResourceManager.GetString("Makes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجوال.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موديل السيارة.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موديلات السيارات.
        /// </summary>
        public static string Models {
            get {
                return ResourceManager.GetString("Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صافى المبلغ.
        /// </summary>
        public static string NetAmount {
            get {
                return ResourceManager.GetString("NetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صافى المبلغ.
        /// </summary>
        public static string NetPrice {
            get {
                return ResourceManager.GetString("NetPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة جديد.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطعة جديدة.
        /// </summary>
        public static string NewPart {
            get {
                return ResourceManager.GetString("NewPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط لاغير.
        /// </summary>
        public static string Only {
            get {
                return ResourceManager.GetString("Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجراء الدفع.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمليات الدفع.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خيارات.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالك القطعة.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان الرئيسي.
        /// </summary>
        public static string ParentLocation {
            get {
                return ResourceManager.GetString("ParentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السمة الرئيسية.
        /// </summary>
        public static string ParentOption {
            get {
                return ResourceManager.GetString("ParentOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القطعة الرئيسية.
        /// </summary>
        public static string ParentPart {
            get {
                return ResourceManager.GetString("ParentPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القطعة.
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموعات.
        /// </summary>
        public static string PartGroups {
            get {
                return ResourceManager.GetString("PartGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فواتير البيع.
        /// </summary>
        public static string PartInvoices {
            get {
                return ResourceManager.GetString("PartInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع السيارت المرتبطة.
        /// </summary>
        public static string PartMakes {
            get {
                return ResourceManager.GetString("PartMakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موديلات السيارات المرتبطة.
        /// </summary>
        public static string PartModels {
            get {
                return ResourceManager.GetString("PartModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم القطعة.
        /// </summary>
        public static string PartName {
            get {
                return ResourceManager.GetString("PartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسماء القطع.
        /// </summary>
        public static string PartNames {
            get {
                return ResourceManager.GetString("PartNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القطعة.
        /// </summary>
        public static string PartNumber {
            get {
                return ResourceManager.GetString("PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم السمة.
        /// </summary>
        public static string PartOptionName {
            get {
                return ResourceManager.GetString("PartOptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سمات القطع.
        /// </summary>
        public static string PartOptions {
            get {
                return ResourceManager.GetString("PartOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصائص أخري للقطعة.
        /// </summary>
        public static string PartOtherOptions {
            get {
                return ResourceManager.GetString("PartOtherOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسماء القطع.
        /// </summary>
        public static string PartsName {
            get {
                return ResourceManager.GetString("PartsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القطعة بالمخزن.
        /// </summary>
        public static string PartsStock {
            get {
                return ResourceManager.GetString("PartsStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطع الغيار بالمخزن.
        /// </summary>
        public static string PartsStocks {
            get {
                return ResourceManager.GetString("PartsStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالات الاستخدام.
        /// </summary>
        public static string PartStatus {
            get {
                return ResourceManager.GetString("PartStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الاستخدام.
        /// </summary>
        public static string PartStatusName {
            get {
                return ResourceManager.GetString("PartStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القطع بالمتجر.
        /// </summary>
        public static string PartStock {
            get {
                return ResourceManager.GetString("PartStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاستهلاك.
        /// </summary>
        public static string PartUsage {
            get {
                return ResourceManager.GetString("PartUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملية الدفع.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدفوعات.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمليات الدفع.
        /// </summary>
        public static string PaymentsList {
            get {
                return ResourceManager.GetString("PaymentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير المدفوعات ،المصروفات ، والتحويلات البنكية..
        /// </summary>
        public static string PaymentsReceiptsList {
            get {
                return ResourceManager.GetString("PaymentsReceiptsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بند المدفوع.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع المصروفات.
        /// </summary>
        public static string PaymentTypes {
            get {
                return ResourceManager.GetString("PaymentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصور.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط التعاقد.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة الإيصال.
        /// </summary>
        public static string PrintReceipt {
            get {
                return ResourceManager.GetString("PrintReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الترتيب.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسة البيع.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحليل المشتريات.
        /// </summary>
        public static string PurchaseAnalysisReport {
            get {
                return ResourceManager.GetString("PurchaseAnalysisReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الشراء.
        /// </summary>
        public static string PurchasePrice {
            get {
                return ResourceManager.GetString("PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الايصال.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الايصال.
        /// </summary>
        public static string ReceiptNo {
            get {
                return ResourceManager.GetString("ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المرجع/الشيك.
        /// </summary>
        public static string RefNo {
            get {
                return ResourceManager.GetString("RefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصنيف الصنع.
        /// </summary>
        public static string RegionalOptionName {
            get {
                return ResourceManager.GetString("RegionalOptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عضوية جديدة.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة تعيين.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحليل المبيعات.
        /// </summary>
        public static string SalesAnalysisReport {
            get {
                return ResourceManager.GetString("SalesAnalysisReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حــفظ الكـــل.
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحـــث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابحث عن قطع غيار.
        /// </summary>
        public static string SearchParts {
            get {
                return ResourceManager.GetString("SearchParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتيجة البحث.
        /// </summary>
        public static string SearchReult {
            get {
                return ResourceManager.GetString("SearchReult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طبيعة البائع.
        /// </summary>
        public static string SellerType {
            get {
                return ResourceManager.GetString("SellerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طبيعة البائع.
        /// </summary>
        public static string SellerTypeName {
            get {
                return ResourceManager.GetString("SellerTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصنيفات الموديل.
        /// </summary>
        public static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصنيف الموديل.
        /// </summary>
        public static string SeriesName {
            get {
                return ResourceManager.GetString("SeriesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأنسب لقطع غيار السيارات.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة ضريبية.
        /// </summary>
        public static string TaxInvoice {
            get {
                return ResourceManager.GetString("TaxInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلى الخزينة/البنك.
        /// </summary>
        public static string ToBank {
            get {
                return ResourceManager.GetString("ToBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحركة اليومية.
        /// </summary>
        public static string TodayTotalCache {
            get {
                return ResourceManager.GetString("TodayTotalCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجمالى.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإشعارات.
        /// </summary>
        public static string TotalNotifications {
            get {
                return ResourceManager.GetString("TotalNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلى سنة.
        /// </summary>
        public static string ToYear {
            get {
                return ResourceManager.GetString("ToYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.3.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض صور القطعة.
        /// </summary>
        public static string ViewImages {
            get {
                return ResourceManager.GetString("ViewImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل فاتورة قطع غيار جديدة..
        /// </summary>
        public static string ViewPartInvoicesList {
            get {
                return ResourceManager.GetString("ViewPartInvoicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الشاصي.
        /// </summary>
        public static string VIN {
            get {
                return ResourceManager.GetString("VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الزوار.
        /// </summary>
        public static string Visits {
            get {
                return ResourceManager.GetString("Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برقم المرجع/الشيك.
        /// </summary>
        public static string WithReferenceCheckNo {
            get {
                return ResourceManager.GetString("WithReferenceCheckNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنة الصنع.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنوات الصنع المرتبطة.
        /// </summary>
        public static string YearMap {
            get {
                return ResourceManager.GetString("YearMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنوات الصنع.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
